### ISSUE TITLE
"StartMoveNumber" option doesn't work with TakeMakeChess?

### ISSUE THREAD

**Issue by nshram** [thomas-maeder/popeye#287] opened 2020-05-22 17:41 UTC
With TakeMakeChess as a condition, putting StartMoveNumber to any value has no effect. The testing always starts with move number 1.
Is this a known issue?

**Comment by JoshuaGreen** [comment] 2020-05-23 01:35
Duplicate of Issue #286.

**Closed by JoshuaGreen** 2020-05-23 01:35 UTC
