### ISSUE TITLE
bug(s?) with Kamikaze under "opti inte"

### ISSUE THREAD

**Issue by andrew-buchanan** [thomas-maeder/popeye#295] opened 2020-07-16 06:04 UTC
There's something odd going on with Kamikaze in Popeye v4.85 - under option intelligent

Example 1:

begi
prot outputp.txt
piec whit kami Ke1 Rd1 Bd4 blac kami Kf8 Pe7 Pf7
opti vari inte
stip h#1.5
end

yields:
  1...kBd4-f6   2.kKf8-e8 kRd1-d8 #
  1...kBd4-f6   2.kPe7-e5 kRd1-d8 #
  1...kBd4-f6   2.kPe7-e6 kRd1-d8 #

without option intelligent:
  1...kBd4-a1   2.kKf8-e8 kRd1-d8 #
  1...kBd4-b2   2.kKf8-e8 kRd1-d8 #
  1...kBd4-c3   2.kKf8-e8 kRd1-d8 #
  1...kBd4-g1   2.kKf8-e8 kRd1-d8 #
  1...kBd4-f2   2.kKf8-e8 kRd1-d8 #
  1...kBd4-e3   2.kKf8-e8 kRd1-d8 #
  1...kBd4-h8   2.kKf8-e8 kRd1-d8 #
  1...kBd4-g7 +   2.kKf8-e8 kRd1-d8 #
  1...kBd4-f6   2.kPe7-e5 kRd1-d8 #
  1...kBd4-f6   2.kPe7-e6 kRd1-d8 #
  1...kBd4-f6   2.kKf8-e8 kRd1-d8 #
  1...kBd4-e5   2.kKf8-e8 kRd1-d8 #
  1...kBd4-a7   2.kKf8-e8 kRd1-d8 #
  1...kBd4-b6   2.kKf8-e8 kRd1-d8 #
  1...kBd4-c5   2.kKf8-e8 kRd1-d8 #

Example 2:

begi
prot kamiout.txt
piec whit Ke1 whit kami Ra1 Ba3 Sc3 Sa6 Pe2 Pf3 Pg2 Ph3 blac Ke8 blac kami Rh8 Rb8 Qb4 Bc8 Sd5 Sc4 Pe7 Pg7
opti vari inte
stip h#3
end

yields:
  1.kQb4*a3[-bkQa3] kSa6-b4   2.Ke8-d8 kRa1-a7   3.kRh8-e8 kSb4-c6 #
  1.kSc4-e5 0-0-0   2.kSe5-f7 kSc3*d5[-wkSd5]   3.kRh8-f8 kSa6-c7 #
  1.kBc8-e6 0-0-0   2.kBe6-f7 kSc3*d5[-wkSd5]   3.kRh8-f8 kSa6-c7 #
  1.0-0 0-0-0   2.kRf8-f7 kSc3*d5[-wkSd5]   3.Kg8-f8 kRd1-d8 #
  1.kRh8-f8 0-0-0   2.kRf8-f7 kSc3*d5[-wkSd5]   3.Ke8-f8 kRd1-d8 #
  1.0-0 kRa1-d1   2.Kg8-h8 kRd1-d4   3.kRf8-g8 kRd4-h4 #
  1.0-0 0-0-0   2.Kg8-h8 kRd1-d4   3.kRf8-g8 kRd4-h4 #

However when run without option intelligent, this gives:
  1.kQb4*a3[-bkQa3] kSa6-b4   2.Ke8-d8 kRa1-a7   3.kRh8-e8 kSb4-c6 #
  1.kSc4-e5 0-0-0   2.kSe5-f7 kSc3*d5[-wkSd5]   3.kRh8-f8 kSa6-c7 #
  1.kSc4-e5 0-0-0   2.kRh8-f8 kSc3*d5[-wkSd5]   3.kSe5-f7 kSa6-c7 #
  1.kSc4-d6 0-0-0   2.kSd6-f7 kSc3*d5[-wkSd5]   3.kRh8-f8 kSa6-c7 #
  1.kSc4-d6 0-0-0   2.kRh8-f8 kSc3*d5[-wkSd5]   3.kSd6-f7 kSa6-c7 #
  1.kBc8-e6 0-0-0   2.kBe6-f7 kSc3*d5[-wkSd5]   3.kRh8-f8 kSa6-c7 #
  1.kBc8-e6 0-0-0   2.kRh8-f8 kSc3*d5[-wkSd5]   3.kBe6-f7 kSa6-c7 #
  1.0-0 kRa1-d1   2.Kg8-h8 kRd1-d4   3.kRf8-g8 kRd4-h4 #
  1.0-0 0-0-0   2.kRf8-f7 kSc3*d5[-wkSd5]   3.Kg8-f8 kRd1-d8 #
  1.0-0 0-0-0   2.Kg8-h8 kRd1-d4   3.kRf8-g8 kRd4-h4 #
  1.kRh8-f8 0-0-0   2.kSc4-e5 kSc3*d5[-wkSd5]   3.kSe5-f7 kSa6-c7 #
  1.kRh8-f8 0-0-0   2.kSc4-d6 kSc3*d5[-wkSd5]   3.kSd6-f7 kSa6-c7 #
  1.kRh8-f8 0-0-0   2.kBc8-e6 kSc3*d5[-wkSd5]   3.kBe6-f7 kSa6-c7 #
  1.kRh8-f8 0-0-0   2.kRf8-f7 kSc3*d5[-wkSd5]   3.Ke8-f8 kRd1-d8 #

Intelligent is way faster, documentation says:
Intelligent = intelligent (quick) solving of helpmate-moremovers. After the intelligent option, the maximum number of solutions per mating position can be given.
It seems there is a default of 1 being applied to max solution number here in Example 2? Is that correct? Surely this does not usually get applied to intelligent helpmates?

In Example 1, there are many genuine solutions taken away by "intelligent".

If this is intended behaviour, and inte is not intended to be combined with kamikaze, please can you indicate clearly in the documentation, in what general circumstances "inte" can reliably be used.

Thanks for all your work - I am incredibly grateful for all you do.

All the best,
Andrew

**Comment by JoshuaGreen** [comment] 2020-08-09 11:45
In debug mode the intelligent mode example yields an [assertion](https://en.wikipedia.org/wiki/Assertion_(software_development)) failure -- we hit line 401 of [`optimisations/intelligent/count_nr_of_moves.c`](https://github.com/thomas-maeder/popeye/blob/master/optimisations/intelligent/count_nr_of_moves.c).  This seems to be because `from_piece` there is (somehow) `Empty`.

**Comment by JoshuaGreen** [comment] 2020-08-17 00:29
One interesting point: In that first example Popeye only counts 13 potential positions in 2+1, but the non-intelligent mode run finds that 15 are actually reachable, hence there should be _at least_ 15 in the intelligent mode count.

**Comment by JoshuaGreen** [comment] 2020-10-01 01:28
@thomas-maeder, I've been trying to work this out, starting with an initial goal of eliminating the [`assert`ion](https://en.wikipedia.org/wiki/Assertion_(software_development)) failure noted above.  Is there any chance that the issue is related to line 28 of [`optimisations/intelligent/mate/goalreachable_guard.c`](https://github.com/thomas-maeder/popeye/blob/develop/optimisations/intelligent/mate/goalreachable_guard.c) and that we need to somehow account for the fact that the capture removed _two_ pieces, either of which may be participating in the mate?

**Comment by JoshuaGreen** [comment] 2020-10-04 00:42
I now doubt that I was looking in the right place with my previous comment.&nbsp; I have found one clue &mdash; if we only ask for one solution per position (with `option inte 1`), then the [`assert`ion](https://en.wikipedia.org/wiki/Assertion_(software_development)) violating goes away, but we still only find 13 target positions at (2 + 1), yielding two solutions.

**Comment by JoshuaGreen** [comment] 2020-10-06 23:56
@andrew-buchanan, I'm now convinced that Popeye intelligent mode simply isn't currently designed to work in Kamikaze mode.  The logic that generates the target positions doesn't seem to generate any that are based on the Kamikaze condition, and the Kamikaze solution it finds in the first example is an accidental discovery -- it's aiming for a position with the wB on f6, the wR on d8, the bK on e8, a bP on f7, and nothing on e7.  I'll try to update Popeye so it makes this clear to the user.  Thanks for bringing this to our attention.

**Comment by JoshuaGreen** [comment] 2020-10-07 03:09
@thomas-maeder, [`feature/fixingIssue295`](https://github.com/thomas-maeder/popeye/tree/feature/fixingIssue295) is my proposed fix for this issue.&nbsp; It merely asserts that intelligent mode doesn't work with Kamikaze pieces.&nbsp; If this looks right, please merge it into [`develop`](https://github.com/thomas-maeder/popeye/tree/develop) and close this ticket.

**Comment by thomas-maeder** [comment] 2021-02-11 06:09
`If this looks right, please merge it into develop`

Just done.

`and close this ticket.`

Going to do.

Please note that it will probably never be useful to document what fairy elements intelligent mode works with.

**Closed by thomas-maeder** 2021-02-11 06:09 UTC

**Comment by JoshuaGreen** [comment] 2021-02-11 12:12
My hesitancy had little to do with concerns of code correctness.  Rather, this particular update is essentially a judgment call, _declaring_ that Popeye cannot, will not support Kamikaze pieces in intelligent mode.  I wasn't willing to make that call on my own.

**Comment by andrew-buchanan** [comment] 2021-02-12 13:12
I am totally ok with this decision. What I would appreciate is an official description of what intelligent mode in fact does, detailed enough so I can determine whether it's relevant for me to apply it to a specific fairy problem.
