### ISSUE TITLE
Intelligent mode bug

### ISSUE THREAD

**Issue by viktoras-pal** [thomas-maeder/popeye#279] opened 2020-04-17 20:38 UTC
BeginProblem
Stipulation h#1
Option Variation NoBoard Intelligent
Pieces
  white  Pb6 Kc4 Rc6h8
  black  Sc5 Ka6
EndProblem

Popeye cannot find solution in Intelligent mode.

**Comment by thomas-maeder** [comment] 2020-04-18 11:04
This turns out out to be a duplicate of issue #257

**Closed** 2020-04-18 11:05 UTC
Labels: bug, duplicate
